#!/bin/bash
#
# See original: https://gist.github.com/younes0/6166191
 
# Check if a composer.json file is present
if [ -f composer.json ]; 
then
    # Detect composer binary
    if which composer >/dev/null; 
	then
        composer='composer'
    elif which composer.phar >/dev/null; 
	then
        composer='composer.phar'
    else
        # Install composer
        curl -s http://getcomposer.org/installer | php >/dev/null
        composer='php composer.phar'
    fi
 
    # Run composer if composer.json is updated
    if [ composer.json -nt composer.lock ]; 
	then
 
        # Install depending on lock file
        echo "composer.lock out of date: installing Composer packages"
        [ ! -f composer.lock ] && $composer install
 
    else
 
        # Regenerating autoload files
        echo "Composer packages up to date"
        $composer dump-autoload
 
    fi
else
	echo "No composer.json present"
fi